### PR TITLE
Add scale-generator exercise

### PR DESCRIPTION
**Pull request by pfertyk**

### CODE REVIEW

**Comment by pfertyk** [comment]
@BNAndras another one copied from Python and ready for review ;)

**Comment by BNAndras** [comment]
Just a heads up but I remember this exercise being deprecated upstream. Tracks can still implement it of course but if the problem-specifications repo recommends a different exercise to be implemented, we should generally implement that one unless we have a reason to keep the deprecated one. So instead of porting accumulate for example, it’s recommended you implement list-ops.

**Review by BNAndras — APPROVED** [review]

**Comment by BNAndras** [comment]
The issue was that the musical theory behind the problem was confusing to some students. Some tracks have kept the exercise, but some have deprecated it. So it's fine to keep it given that there's no recommended replacement exercise. I'm just highlighting this exercise has some problems, but it might still be a net plus to have the exercise.

**Comment by pfertyk** [comment]
Acknowledged @BNAndras :+1: For now, I'm adding this exercise, and if we have a good replacement in the future, I will deprecate this one ;)

**Pull request merged**
