### PR TITLE
Update Godot Engine typing

### PR DESCRIPTION
**Pull request by pfertyk**

### CODE REVIEW

**Comment by pfertyk** [comment]
This is weird ... I thought we already added `gradual` as a valid typing here:
https://github.com/exercism/configlet/pull/842
@ErikSchierboom do I need to update the Configlet action?

**Comment by BNAndras** [comment]
The CI uses the latest release of configlet, which is 4.0.0-beta.16 from October 2023, but that predates the PR adding `gradual`. I think you'll need to wait until the next release of configlet, but I'm not privy to when that might be. Perhaps we can push a beta 17 release sooner than later?

**Comment by ErikSchierboom** [comment]
> Perhaps we can push a beta 17 release sooner than later?

We'll try and release ASAP

**Comment by pfertyk** [comment]
Yup, now it works! Thank you! :)

**Pull request merged**
