### PR TITLE
[New exercise]: leap

### PR DESCRIPTION
**Pull request by BNAndras**
I'll park this for now and try running the test runner on the exercise later this week.

### CODE REVIEW

**Comment by BNAndras** [comment]
@pfertyk `gdlint` complains about unused function arguments, but that is expected behavior in the stubs that have functions with arguments. Is there a way to customize gdlint's rules to avoid this specific check?

**Comment by pfertyk** [comment]
@BNAndras yes, it seems that it's possible, either globally or per method:
https://github.com/Scony/godot-gdscript-toolkit/wiki/3.-Linter#tweaking-default-check-settings

**Comment by BNAndras** [comment]
I'll take a look. I'd rather disable that particular check globally rather than adding overrides inside the stub. That might confuse the student since the override would be there for CI purposes only and actually has no bearing on their solution.

**Review by pfertyk — CHANGES_REQUESTED** [review]
The changes look good, but the test cases need to be updated to follow the new format :)

**Comment by BNAndras** [comment]
Shouldn't the CI fail then if I'm not using a properly configured test suite?

**Comment by pfertyk** [comment]
No, unfortunately :) The old format required a `TEST_CASES` array and iterated over all its values. The new format expects that each test is a method, its name starting with `test_`. So, if the test file doesn't have any methods, no tests will be executed ;)

I will prepare a PR for logging each test execution, just to be sure that the runner is doing its job :P

**Review by pfertyk — APPROVED** [review]

**Pull request merged**
