### PR TITLE
Pin GDScript Toolkit to v4.1

### PR DESCRIPTION
**Pull request by pfertyk**
This is the closest we can get to the Godot Engine's version used by our test runner: v4.1.1 .

### CODE REVIEW

**Comment by pfertyk** [comment]
@BNAndras what do you think?

**Comment by BNAndras** [comment]
I'd run that by @ErikSchierboom since generally we want to pin a specific commit for the CI. That gives us reproducible builds.

**Comment by pfertyk** [comment]
Yeah, I'm working on it ... in this case, the specific commit didn't work. But, apparently, neither does a specific tag. Perhaps we will have to leave it as it was, or update Godot Engine earlier than expected :P

**Comment by BNAndras** [comment]
I think the SHA for v4.1.0 is af9a6e36935fe7319aa559ca068ef8f2392d99c3. The next upgrade was to v4.2.0 so that's probably not what you wanted.

**Comment by pfertyk** [comment]
That's what I had originally, but that didn't work :( I wonder if maybe the old version is no longer supported for some reason.

**Comment by ErikSchierboom** [comment]
Looking at [the logs](https://github.com/exercism/gdscript/actions/runs/7253270262/job/19759516393?pr=26), it looks like version 4.1. did not yet contain the GitHub Actions bits:

> can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action 'Scony/godot-gdscript-toolkit@af9a6e36935fe7319aa559ca068ef8f2392d99c3'.

**Comment by pfertyk** [comment]
I'm closing this one, since we decided not to use this toolkit for now (it causes more problems than it solves :( ).

**Pull request closed without merging**
